[typescript] avoid error in future Typescript 4.1
fingerprintjs/fingerprintjs pull request #575
Opened 2020-10-24 20:59 UTC by Manu1400

see https://github.com/microsoft/TypeScript/issues/41155

2020-10-24 21:03 UTC, Manu1400 commented
In Typescript@next (4.1.0-beta) : https://www.typescriptlang.org/play?ts=4.1.0-beta#code/MYewdgzgLgBGMF44EMBuBLA5sqIBOAUAQKYAeADvrACbEBmyArgDax2NjBTrgybFQAMsjCZGyfhAAUASgBcMaHnSiA2gF0NMAN4EYMUJFh5iEFlAVKVmDVqQai+w9BjMRYicURwAdG9Hi-DAAPsG+jBDEeMIBniFhYD4ARnggAO6R0e6BXqG+EACe0MQAtjEe-How6HQwUv4VXgCECEgctHQqxNQyOlX6JmasPuQRABZSqg056jJVAL6OvtOeEEs1dQCCeHjIBT7oENu7BVKJK5Iyvbr6+gD0dzAAylDIeNyiMHSpJTAAwmMfuhGL8ABwANgANDAoGMol5DjBwMwCjBkIprMwvKhkMxGAj4AADMBoLA4fB+bKeQnVeAASU4IEwYHQuBgJRAtDk-RgDxhcJgOLxXhAtWJpOwuDwlNi-EJPhgABU4SY6PgvLDsbj8dUINVmerqLT+YiUulMj4eRspE0pIcAUCQbIYAAyF26h0gErAkoQgDyeAAcsQ0lFZFc+rdboNzCNxmcZY09cg9VY1LMeYt9PMYMRmJFqrUpFACuRiKLllTJIhWjAAORpzB16485ywC6mbznKudlOKKDKURWosdiAtqMDUyx0YQCajnwQcjMVlSOuQ5tzKNZmCLKomKCMPDwGOsAjzIA

2020-10-24 23:23 UTC, Finesse commented on src/sources/languages.ts
> +      result.push(n.languages as string[])
Thanks for letting us know! But ignoring TypeScript warnings isn’t a good solution. Please make a writable copy of the array instead:

```js
result.push([...n.languages])
```

2020-10-24 23:26 UTC, Finesse requested changes

2020-10-24 23:26 UTC, Finesse commented on src/sources/languages.ts
> +      result.push(n.languages as string[])
Thanks for letting us know! But ignoring TypeScript warnings isn’t a good solution. Please make a writable copy of the array instead:

```js
result.push([...n.languages])
```

2020-10-30 13:15 UTC, Toronto00 approved these changes

2020-11-16 12:49 UTC, Valve commented
Closing due to inactivity. Please feel free to reopen with additional updates and/or comments.

2020-11-16 12:49 UTC, closed without merging